version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001" # Map frontend to port 3001
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000"
    environment:
      - NODE_ENV=development
